# NODE + EXPRESS BÁSICO

## INTRODUÇÃO

## INSTALANDO O AMBIENTE

## INSTALANDO DEPENDENCIAS

## ESTRUTURA MÍNIMA DE UM APP NODEJS

## MEU PRIMEIRO: LET'S ROCK BABY!

## ACRESCENTANDO O MOLHO: EXPRESS

## MEU SEGUNDO: LET'S ROCK BABY!

## ESTRUTURA BÁSICA APP DO EXPRESS

## ROTEAMENTO E ARQUIVOS ESTÁTICOS
